Response = {u'responseData': {
    u'cursor': {u'moreResultsUrl': u'http://www.google.com/search?oe=utf8&ie=utf8&source=uds&start=0&hl=en&q=1',
                u'estimatedResultCount': u'180000000', u'searchResultTime': u'0.28', u'resultCount': u'180,000,000',
                u'pages': [{u'start': u'0', u'label': 1}, {u'start': u'8', u'label': 2}, {u'start': u'16', u'label': 3},
                           {u'start': u'24', u'label': 4}, {u'start': u'32', u'label': 5},
                           {u'start': u'40', u'label': 6},
                           {u'start': u'48', u'label': 7}, {u'start': u'56', u'label': 8}], u'currentPageIndex': 0},
    u'results': [
        {u'GsearchResultClass': u'GwebSearch', u'visibleUrl': u'www.google.com',
         u'titleNoFormatting': u'Google +1 Button',
         u'title': u'Google +<b>1</b> Button', u'url': u'http://www.google.com/%2B1/button/',
         u'cacheUrl': u'http://www.google.com/search?q=cache:6ISXikertkcJ:www.google.com',
         u'unescapedUrl': u'http://www.google.com/+1/button/',
         u'content': u'+<b>1</b> gets conversations going. Click the +<b>1</b> button to give something your public   stamp of approval. Then, if you want to share right away, add a comment and <b>...</b>'},
        {u'GsearchResultClass': u'GwebSearch', u'visibleUrl': u'developers.google.com',
         u'titleNoFormatting': u'+1 Button - Google+ Platform \u2014 Google Developers',
         u'title': u'+<b>1</b> Button - Google+ Platform \u2014 Google Developers',
         u'url': u'https://developers.google.com/%2B/plugins/%2B1button/',
         u'cacheUrl': u'http://www.google.com/search?q=cache:wafryvFfkM8J:developers.google.com',
         u'unescapedUrl': u'https://developers.google.com/+/plugins/+1button/',
         u'content': u'Nov 29, 2012 <b>...</b> You can add and customize the +1   button to meet the needs <b>...</b>'},
        {u'GsearchResultClass': u'GwebSearch', u'visibleUrl': u'en.wikipedia.org',
         u'titleNoFormatting': u'1 (number) - Wikipedia, the free encyclopedia',
         u'title': u'<b>1</b> (number) - Wikipedia, the free encyclopedia',
         u'url': u'http://en.wikipedia.org/wiki/1_(number)',
         u'cacheUrl': u'http://www.google.com/search?q=cache:btIxqCxX24UJ:en.wikipedia.org',
         u'unescapedUrl': u'http://en.wikipedia.org/wiki/1_(number)',
         u'content': u'<b>1</b> (one; pron.: /\u02c8w\u028cn/ or UK /\u02c8w\u0252n/) is a number, a numeral, and the name of the   glyph representing that number. It represents a single entity, the unit of <b>...</b>'},
        {u'GsearchResultClass': u'GwebSearch', u'visibleUrl': u'twitter.com', u'titleNoFormatting': u'1 (1) on Twitter',
         u'title': u'<b>1</b> (<b>1</b>) on Twitter', u'url': u'https://twitter.com/1',
         u'cacheUrl': u'http://www.google.com/search?q=cache:p1oOA3blciMJ:twitter.com',
         u'unescapedUrl': u'https://twitter.com/1',
         u'content': u'The latest from <b>1</b> (@<b>1</b>). <b>...</b> Tweets \xb7 Following \xb7 Followers \xb7 Favorites \xb7 Lists. Follow   <b>1</b>. Full name. Email. Password. Worldwide trends. \xb7 Change. \xa9 2013 Twitter <b>...</b>'},
        {u'GsearchResultClass': u'GwebSearch', u'visibleUrl': u'twitter.com',
         u'titleNoFormatting': u'Twitter / Search - #1', u'title': u'Twitter / Search - #<b>1</b>',
         u'url': u'https://twitter.com/search%3Fq%3D%25231',
         u'cacheUrl': u'http://www.google.com/search?q=cache:EKwTP28dy0MJ:twitter.com',
         u'unescapedUrl': u'https://twitter.com/search?q=%231',
         u'content': u'<b>1</b>) Harry didn&#39;t set up Louis and Eleanor 2) Harry and Eleanor aren&#39;t even friends   <b>...</b> <b>1</b>:45 CT, check out @RunnerSpace_com for the live webcast. pic.twitter.com/ <b>...</b>'},
        {u'GsearchResultClass': u'GwebSearch', u'visibleUrl': u'www.youtube.com', u'titleNoFormatting': u'+1 - YouTube',
         u'title': u'+<b>1</b> - YouTube', u'url': u'http://www.youtube.com/playlist%3Flist%3DPL967AEA43B29EB01A',
         u'cacheUrl': u'http://www.google.com/search?q=cache:8PyXFtQyAdEJ:www.youtube.com',
         u'unescapedUrl': u'http://www.youtube.com/playlist?list=PL967AEA43B29EB01A',
         u'content': u'Go backstage as Pitchfork&#39;s +<b>1</b> in this series dedicated to capturing live   performances.'},
        {u'GsearchResultClass': u'GwebSearch', u'visibleUrl': u'www.onepercentfortheplanet.org',
         u'titleNoFormatting': u'1% for the Planet | Home', u'title': u'<b>1</b>% for the Planet | Home',
         u'url': u'http://www.onepercentfortheplanet.org/en/',
         u'cacheUrl': u'http://www.google.com/search?q=cache:-Csv13pNa8oJ:www.onepercentfortheplanet.org',
         u'unescapedUrl': u'http://www.onepercentfortheplanet.org/en/',
         u'content': u'<b>1</b>% for the Planet is an alliance of businesses that donate at least <b>1</b>% of their   annual revenues to environmental organizations worldwide.'},
        {u'GsearchResultClass': u'GwebSearch', u'visibleUrl': u'money.cnn.com',
         u'titleNoFormatting': u'What it takes to get into the top 1% - Nov. 20, 2012',
         u'title': u'What it takes to get into the top <b>1</b>% - Nov. 20, 2012',
         u'url': u'http://money.cnn.com/2012/11/20/news/economy/top-1-percent/index.html',
         u'cacheUrl': u'http://www.google.com/search?q=cache:ZPjrwQEqvcMJ:money.cnn.com',
         u'unescapedUrl': u'http://money.cnn.com/2012/11/20/news/economy/top-1-percent/index.html',
         u'content': u'Nov 20, 2012 <b>...</b> You needed an adjusted gross income of $370000 to get into the top <b>1</b>% in 2010,   up from $352000 a year earlier.'}]},
            u'responseDetails': None, u'responseStatus': 200}
queue = ([u'http://www.google.com/%2B1/button/', u'https://developers.google.com/%2B/plugins/%2B1button/',
          u'http://en.wikipedia.org/wiki/1_(number)', u'https://twitter.com/1',
          u'http://googleblog.blogspot.com/2011/03/1s-right-recommendations-right-when-you.html',
          u'http://www.onepercentfortheplanet.org/en/',
          u'http://www.youtube.com/playlist%3Flist%3DPL967AEA43B29EB01A',
          u'http://www.washingtonpost.com/blogs/ezra-klein/post/who-are-the-1-percenters/2011/10/06/gIQAn4JDQL_blog.html',
          u'http://money.cnn.com/2012/11/20/news/economy/top-1-percent/index.html', u'http://plusonemusic.net/'])