<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">

<head profile="http://gmpg.org/xfn/11">
 <title> PARS &#8211; Time Inc. Reprints</title>   
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="icon" href="favicon.ico" type="image/x-icon" /> 
 <link rel="alternate" type="application/rss+xml" title="PARS - Time Inc. Reprints &raquo; Feed" href="http://www.timeincreprints.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="PARS - Time Inc. Reprints &raquo; Comments Feed" href="http://www.timeincreprints.com/comments/feed/" />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.timeincreprints.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.timeincreprints.com/wp-includes/wlwmanifest.xml" /> 
<link rel='index' title='PARS - Time Inc. Reprints' href='http://www.timeincreprints.com' />
<meta name="generator" content="WordPress 2.9.2" />

<!-- Start Of Script Generated By cforms v11.4 [Oliver Seidel | www.deliciousdays.com] -->
<link rel="stylesheet" type="text/css" href="http://www.timeincreprints.com/wp-content/plugins/cforms/styling/cforms.css" />
<script type="text/javascript" src="http://www.timeincreprints.com/wp-content/plugins/cforms/js/cforms.js"></script>
<!-- End Of Script Generated By cforms -->

 
<link rel="stylesheet" href="http://www.timeincreprints.com/wp-content/themes/timeincreprints/css/style.css" media="screen" />
<!--[if IE 8]><link rel="stylesheet" href="http://www.timeincreprints.com/wp-content/themes/timeincreprints/css/style_ie8.css" type="text/css" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" href="http://www.timeincreprints.com/wp-content/themes/timeincreprints/css/style_ie7.css" type="text/css" media="screen" /><![endif]-->

 <link rel="stylesheet" href="http://www.timeincreprints.com/wp-content/themes/timeincreprints/css/cforms_dev.css" media="screen" />   
<script type="text/javascript" src="http://www.timeincreprints.com/wp-content/themes/timeincreprints/js/jquery-1.4.2.min.js"></script>   

 

<script language="javascript" type="text/javascript" >  
$(document).ready (function () {      
 var path =  "/" ;
 var subpage = "" ; 

   if ( path )
     $('.right_menu a[href="' + path + '"]').addClass('active');  
     //if (path != '/' && ( subpage == 'clients' || subpage == 'publishers' ) )  $('#header').addClass('sub_header');
 });
</script>

</head>

<body>
    <div class="layout">
        <div class="header" id="header">
            <h1><a href="/" class="logo" title="Pars. International Corp."></a></h1>
            <ul class="right_menu">
                <li><a href="/">Home</a></li>
                <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li> 
                <li><a href="/services/">Services</a></li>
                <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li> 
                <li><a href="/permissions-covers/">Permissions/Covers</a></li>
                <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
                <li><a href="/faqs/">FAQs</a></li>
                <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
                <li><a href="/publisher-info/">Publisher Info</a></li>
            </ul>

         
</div>

 <div class="sub_flash">
                                         <img src="http://www.timeincreprints.com/wp-content/files_flutter/1304611787timeincbanner.jpg " />
						      
        </div>
                <div class="subpage_cols">
            <div class="subpage_left">
                   <div class="left_btm_text" > <h4>Thank you for your interest in repurposing Time Inc. content. PARS International Corp. is the authorized reprint, permissions/licensing agent for Time Inc. We offer a full suite of products and services ranging from hardcopy and electronic reprints to plaques, posters, and permissions/licensing, including photocopies.</h4>
<div></div>  </div> 
                    <img src="http://www.timeincreprints.com/wp-content/themes/timeincreprints/images/spacer.gif" height="105" alt="" />
                    <div class="btn_collect">
                        <a href="/reprint-products-quote-request/" class="quote_btn">&nbsp;</a>
                        <a href="/permissions-licensing-quote-request/" class="license_quote_btn"></a>
                    </div> 
  			</div>
            
            <div class="subpage_center">
                <h2>Benefits</h2>
<h5>High-impact uses of article reprints include:</h5>
<ul class="center_list">
	<li><span>Direct Mail</span></li>
	<li><span>Website Enhancement</span></li>
	<li><span>Corporate Literature</span></li>
	<li><span>Trade Show Collateral &amp; Corporate Giveaways</span></li>
	<li><span>Corporate, Professional, Educational Training &amp; Recruitment Materials</span></li>
</ul>
<a class="big_link" href="/clients/benefits/"></a>   
            </div>
            <div class="subpage_right">
                <h2><a href="/clients/services/">Services</a></h2>
<ul class="right_list">
	<li><a href="/services/reprints/">Reprints</a></li>
	<li><a href="/services/e-prints/">E-Prints</a></li>
	<li><a href="http://www.timeincreprints.com/services/permission-licensing/">Permissions/Covers</a></li>
	<li><a href="/services/speiality-posters-postcards-counter-cards-plaques/">Specialty Posters, Postcards, Counter Cards, Plaques</a></li>
</ul>
<a class="big_link" href="/services/">view all services</a>   
                <div class="computer_img"></div>
            </div>
            
            
     
            
</div>   
            <div class="footer_menu">
                <ul class="footer_left">
                    <li><a href="/">PARS Home</a></li>
                    <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
                    <li><a href="/about-us/">About Us</a></li>
                    <li>&nbsp;&nbsp;|&nbsp;&nbsp;</li>
                    <li><a href="/contact-us/">Contact Us</a></li>
                </ul>
                <p class="footer_right">
                    &copy; 2012 PARS International Corp. All 
rights reserved | <a href="/privacy-policy/">Privacy Policy</a>
                </p>
            </div>
        </div>
    </div> 
    
     
    
     <script type="text/javascript">  
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-12377243-3']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })(); 
     </script>

</body>
</html>
           

