<!DOCTYPE HTML>
<html lang="en-US">
<head>
        <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title> ZeOmega Software</title>
    <link rel="pingback" href="http://www.zeomega.com/xmlrpc.php" />
    <link rel="alternate" type="application/rss+xml" title="ZeOmega Software" href="http://www.zeomega.com/feed/" />

    <link rel="alternate" type="application/rss+xml" title="ZeOmega Software &raquo; Feed" href="http://www.zeomega.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="ZeOmega Software &raquo; Comments Feed" href="http://www.zeomega.com/comments/feed/" />
<link rel="alternate" type="application/rss+xml" title="ZeOmega Software &raquo; ZeOmega &#8211; Disease, Care and Utilization Management Software Comments Feed" href="http://www.zeomega.com/zeomega-disease-care-and-utilization-management-software/feed/" />
<link rel='stylesheet' id='layerslider_css-css'  href='http://www.zeomega.com/wp-content/plugins/LayerSlider/css/layerslider.css?ver=3.5.0' type='text/css' media='all' />
<script type='text/javascript' src='http://www.zeomega.com/wp-includes/js/swfobject.js?ver=2.2-20120417'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-includes/js/jquery/jquery.js?ver=1.8.3'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-content/plugins/LayerSlider/js/layerslider.kreaturamedia.jquery.js?ver=3.5.0'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-content/plugins/LayerSlider/js/jquery-easing-1.3.js?ver=1.3.0'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-content/uploads/wpcu3er/jquery.cu3er.js?ver=3.5.1'></script>
<link rel='canonical' href='http://www.zeomega.com/' />
<link href="http://www.zeomega.com/wp-content/themes/Sterling/style.css" rel="stylesheet" type="text/css" media="screen" />
<link href="http://www.zeomega.com/wp-content/themes/Sterling/css/primary-blue.css" rel="stylesheet" type="text/css" media="screen" />
<link href="http://www.zeomega.com/wp-content/themes/Sterling/css/_mobile.css" rel="stylesheet" type="text/css" media="screen" />
<link rel="shortcut icon" href="http://www.zeomega.com/wp-content/uploads/favicon.ico"/>
<!--styles generated by site options-->
<style type='text/css'>
a, a:hover, h1, h2, h3, h4, h5, h6 header *, dl dt.current, .current-menu-item a, .current-menu-parent a, .current-menu-parent ul .current-menu-item a, .current_page_parent a, .current-menu-ancestor a, .current-menu-ancestor .sub-menu .current-menu-ancestor a, .current-menu-ancestor .sub-menu .current-menu-ancestor .sub-menu .current-menu-item a, .pagination .current:link, .pagination .current:visited, .post-details a:link, .post-details a:visited, aside a:visited, .postinfo a, .comment-author, .comment-text a, .tt-icon span, .tt-comment-count, .sidebar .subnav .has_subnav .current_subpage a, .sidebar .subnav .has_subnav .current_subpage a:hover, .submenu .current, .pagination .current:link, .pagination .current:visited, .meta a:link, .wp-pagenavi .current, .article_preview strong a, .article_preview strong a:hover, .sitemap-title, .faq-content .faq-heading, .faq-questions ol, .callout-heading, .member-contact-phone, #home-marketing-icons strong, .faq-questions a:hover, .s-one ul li a, .s-one .current-page-ancestor a, .s-one .current-page-ancestor ul li a, .home-vertical-sidebar .widget-heading, .tt-icon strong {
color: #3b9469;
}

a.tt-button.green {
background-position: 0 -252px;
border: 1px solid #3b9469;
color: #3b9469;
}

body .tt-overlay {
background: url(/wp-content/uploads/banner-zeomega.png) center center no-repeat;
}

@media screen and (min-width: 800px){
header nav {
margin-left: 240px;
}
}

.current-menu-ancestor a {
color: #a65b42;
}

#banner-search {
position:inherit;
margin: -.4em .3em 1em 0;
float: right;
}

#gallery-outer-wrap .one_fourth {
min-height:440px;
}
h1, h2, h3, h4, h5, h6 {
margin:.2em 0 .2em 0;
}
.crispsearch {
font-weight:bold;
margin-top:10px;
}
body .page-not-found {
background:none;
height:auto;
padding: 20px;
margin: 0;
}

.findsearch #s{
float:left;
}

.tz_tweet_widget ul {
font-family: HelveticaNeue-Regular,Helvetica Neue,Helvetica,Arial,sans-serif;
font-style: normal;
list-style-image: none;
}

.sidebar .subnav ul .has_subnav ul a, .sidebar .subnav ul .has_subnav ul a:hover {
background: none;
}

.page-id-293 .sidebar .subnav ul .has_subnav ul a, .page-id-293 .sidebar .subnav ul .has_subnav ul a:hover, .page-id-289 .sidebar .subnav ul .has_subnav ul a, .page-id-289 .sidebar .subnav ul .has_subnav ul a:hover, .page-id-291 .sidebar .subnav ul .has_subnav ul a, .page-id-291 .sidebar .subnav ul .has_subnav ul a:hover {
background: none;
}

.widget_recent_entries ul {
list-style-image: none;
}

.link-photo {
width:160px;
height:125px;
margin-left: 1em;
margin-bottom: .1em;
margin-top: .5em;
}

.index-button {
text-align:right;
}

a.tt-button {
background-image: url(/wp-content/uploads/zeomega-button-sprite.png);
}

a.tt-button.green {
color: #FFFFFF;
text-decoration:none;
border-color:#477712;
font-weight: 400;
letter-spacing: .14em;
}

.tt-contentbox-title span {
text-transform: none;
font-size: 14px;
}

.linksmall {
word-wrap: break-word;
font-size:12px;
margin-top: -15px;
line-height: 1em;
margin-left:6px;
}

p {
padding:0 3px 0 3px;
}

.linkbutton {
margin-top:-10px;
text-align:right;
}
.large-callout p {
font-size: 1.4em;
background: #EEE;
margin: .1em;
padding: 1em;
}
.page_content h1, .page_content h2, .page_content h3, .page_content h4, .page_content h5, .page_content h6 {
line-height: 1.4em;
}
.slidertop {
font-size: 2em;
padding: .5em;
line-height: 1.2em;
}

.slidersub {
font-size: 1.4em;
line-height: 1.5em;
padding: .8em;
}

b {
font-weight:800;
}

.page_content ul, .page_content_right ul {
margin-left:2em;
}

header .sub-menu a {
font-size:13px;
}

.contentlist {
list-style-image: none;
list-style-type: disc;
}

.linkbutton a, .index-button a {
text-decoration:none;
}

.img-portrait img {
padding-top:2em;
}

.img-exec img {
padding-top:1em;
}

.tt-icon {
padding: 4px 0 4px 60px;
}

.home-vertical-sidebar {
margin-bottom:20px;
padding-right:1em;
}

.home-vertical-sidebar br {
display:none;
}

.home-vertical-sidebar span {
display:block;
font-size:14px;
margin-bottom:8px;
}

a.tt-button.white {
color: #D14414;
}

.sliders {
font-smooth:always;
}

.tt-content-style-sky-blue a:hover  {
color: #53C5FE;
}

.tt-content-style-fire a:hover {
color: #FE8A0B;
}

.tt-content-style-lime-green a:hover {
color: #AED613;
}

.rss {
display:none;
}

.sidebar li, ul {
list-style-image: url(/wp-content/uploads/zeomega-bullet.gif);
}

.full-halves {
max-width:325px;
float:left;
margin-right:.5em;
}

aside .subnav li {
list-style-image: none;
}
body,html{background-color:#BCCBD7 !important;}
body,html{background-image:url(http://www.zeomega.com/wp-content/themes/Sterling/images/body-backgrounds/null.png) !important;background-position:left top !important;background-repeat:repeat !important;}
#tt-boxed-layout {-moz-box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);-webkit-box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.5);}
.top-aside{background:none !important;background-color:#81B407 !important;}
.banner, .banner-slider, .small_banner{background:none !important;background-color:#81B407 !important;}
footer{background:none !important;background-color:#81B407 !important;}
.tt-overlay{background:url(http://www.zeomega.com/wp-content/themes/Sterling/images/banner-overlays/banner-diagonal.png) center center no-repeat;}
.top-aside{padding:8px 0;}
.small_banner {padding:25px 0;}
.footer-content {padding:20px 0;}
header {padding:32px 0;}
h1,h1 a,h1 a:hover{color:#D14414;}
h2,h2 a,h2 a:hover{color:#D14414;}
h3,h3 a,h3 a:hover{color:#D14414;}
h4,h4 a,h4 a:hover{color:#D14414;}
h5,h5 a,h5 a:hover{color:#D14414;}
h6,h6 a,h6 a:hover{color:#D14414;}
.widget-heading{color:#D14414;}
.current-menu-item a,.current-menu-parent a,.current-menu-parent ul .current-menu-item a,.current-menu-ancestor ul .current-menu-ancestor a,.current_page_parent a, header a:hover{color:#D14414 !important;}
</style>

    <!--[if lt IE 9]>
        <link rel="stylesheet" href="http://www.zeomega.com/wp-content/themes/Sterling/css/IE.css" />
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <script type="text/javascript" src="http://www.zeomega.com/wp-content/themes/Sterling/framework/js/IE.js"></script>
        <script type="text/javascript" src="http://www.zeomega.com/wp-content/themes/Sterling/framework/js/respond.js"></script>
    <![endif]-->

    <!-- Styles generated by custom page styling options. -->
<style type="text/css">body, html {background-color:# !important;}</style>
</head>
<body class="home page page-id-6 page-parent page-template page-template-page-template-home-jquery-php">
<div id="tt-boxed-layout">    <aside class="top-aside clearfix">
        <div class="center-wrap">
            <div class="one_half">
                <div class="sidebar-widget widget_nav_menu"><span class="display-none">Menu</span><ul class="custom-menu"></ul></div>            </div><!-- end .top-toolbar-left -->

            <div class="one_half">
                <div class="sidebar-widget social_widget">



<ul class="social_icons">
<li><a href="http://www.zeomega.com/feed/" onclick="window.open(this.href);return false;" class="rss">RSS</a></li>
<li><a href="http://twitter.com/zeomega" class="twitter" onclick="window.open(this.href);return false;">Twitter</a></li>
<li><a href="https://www.facebook.com/ZeOmega" class="facebook" onclick="window.open(this.href);return false;">Facebook</a></li>
<li><a href="http://www.linkedin.com/company/zeomega" class="linkedin" onclick="window.open(this.href);return false;">LinkedIn</a></li>
</ul>

        </div>            </div><!-- end .top-toolbar-right -->
        </div><!-- end .center-wrap -->
        <div class="top-aside-shadow"></div>
    </aside>
    <header>
        <div class="center-wrap">
            <div class="companyIdentity">
                                                            <a href="http://www.zeomega.com"><img src="/wp-content/uploads/zeomega_logo6.png" alt="ZeOmega Software" /></a>
                                                </div><!-- end .companyIdentity -->
            <nav>
                <ul>
                    <li id="menu-item-263" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-263"><a href="http://www.zeomega.com/who-we-serve/">Who We Serve</a>
<ul class="sub-menu">
	<li id="menu-item-314" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-314"><a href="http://www.zeomega.com/who-we-serve/payers/">Payer Organizations</a>
	<ul class="sub-menu">
		<li id="menu-item-267" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-267"><a href="http://www.zeomega.com/who-we-serve/payers/commercial-health-plans/">Commercial Health Plans</a></li>
		<li id="menu-item-273" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-273"><a href="http://www.zeomega.com/who-we-serve/payers/medicaid-health-plans/">Medicaid Health Plans</a></li>
		<li id="menu-item-274" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-274"><a href="http://www.zeomega.com/who-we-serve/payers/medicare-health-plans/">Medicare Health Plans</a></li>
		<li id="menu-item-272" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-272"><a href="http://www.zeomega.com/who-we-serve/payers/integrated-delivery-networks/">Integrated Delivery Networks</a></li>
		<li id="menu-item-268" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-268"><a href="http://www.zeomega.com/who-we-serve/payers/community-health-plans/">Community Health Plans</a></li>
		<li id="menu-item-266" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-266"><a href="http://www.zeomega.com/who-we-serve/payers/care-management-vendors/">Care Management Vendors</a></li>
		<li id="menu-item-278" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-278"><a href="http://www.zeomega.com/who-we-serve/payers/quality-improvement-organizations/">Quality Improvement Organizations</a></li>
		<li id="menu-item-279" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-279"><a href="http://www.zeomega.com/who-we-serve/payers/third-party-administrators/">Third Party Administrators</a></li>
		<li id="menu-item-269" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-269"><a href="http://www.zeomega.com/who-we-serve/payers/employers-or-self-insured/">Employers &#038; Self-Insured</a></li>
		<li id="menu-item-277" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-277"><a href="http://www.zeomega.com/who-we-serve/payers/physician-review-organizations/">Physician Review Organizations</a></li>
	</ul>
</li>
	<li id="menu-item-313" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-313"><a href="http://www.zeomega.com/who-we-serve/providers/">Provider Organizations</a>
	<ul class="sub-menu">
		<li id="menu-item-270" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-270"><a href="http://www.zeomega.com/who-we-serve/providers/hospitals-health-systems/">Hospitals &#038; Health Systems</a></li>
		<li id="menu-item-1326" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1326"><a href="http://www.zeomega.com/who-we-serve/providers/integrated-delivery-networks/">Integrated Delivery Networks</a></li>
		<li id="menu-item-276" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-276"><a href="http://www.zeomega.com/who-we-serve/providers/physician-group-practices/">Physician Group Practices</a></li>
		<li id="menu-item-271" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-271"><a href="http://www.zeomega.com/who-we-serve/providers/independent-physician-associations/">Independent Physician Associations</a></li>
		<li id="menu-item-265" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-265"><a href="http://www.zeomega.com/who-we-serve/providers/ancillary-service-providers/">Ancillary Service Providers</a></li>
	</ul>
</li>
	<li id="menu-item-312" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-312"><a href="http://www.zeomega.com/who-we-serve/shared-risk-entities/">Value-based Care</a>
	<ul class="sub-menu">
		<li id="menu-item-264" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-264"><a href="http://www.zeomega.com/who-we-serve/shared-risk-entities/accountable-care-organizations/">Accountable Care Organizations</a></li>
		<li id="menu-item-275" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-275"><a href="http://www.zeomega.com/who-we-serve/shared-risk-entities/patient-centered-medical-homes/">Patient Centered Medical Homes</a></li>
	</ul>
</li>
</ul>
</li>
<li id="menu-item-258" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-258"><a href="http://www.zeomega.com/what-we-provide/">What We Provide</a>
<ul class="sub-menu">
	<li id="menu-item-259" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-259"><a href="http://www.zeomega.com/what-we-provide/jiva/">Jiva Solutions</a></li>
	<li id="menu-item-262" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-262"><a href="http://www.zeomega.com/what-we-provide/zeomega-services/">Software Services</a></li>
	<li id="menu-item-284" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-284"><a href="http://www.zeomega.com/what-we-provide/zeomega-support-services/">Customer Support</a></li>
</ul>
</li>
<li id="menu-item-253" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-253"><a href="http://www.zeomega.com/about-zeomega-software-solutions/">About</a>
<ul class="sub-menu">
	<li id="menu-item-324" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-324"><a href="http://www.zeomega.com/about-zeomega-software-solutions/zeomega-company-overview/">Company Overview</a></li>
	<li id="menu-item-256" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-256"><a href="http://www.zeomega.com/about-zeomega-software-solutions/zeomega-management-team/">Our Team</a></li>
	<li id="menu-item-329" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-329"><a href="http://www.zeomega.com/about-zeomega-software-solutions/zeomega-board-of-directors/">Board of Directors</a></li>
	<li id="menu-item-255" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-255"><a href="http://www.zeomega.com/about-zeomega-software-solutions/zeomega-associations/">Associations</a></li>
	<li id="menu-item-257" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-257"><a href="http://www.zeomega.com/about-zeomega-software-solutions/our-partners/">Partners</a></li>
	<li id="menu-item-248" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-248"><a href="http://www.zeomega.com/zeomega-disease-care-and-utilization-management-software/careers-at-zeomega/">Careers</a></li>
	<li id="menu-item-249" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-249"><a href="http://www.zeomega.com/zeomega-disease-care-and-utilization-management-software/contact-zeomega-2/">Contact</a></li>
</ul>
</li>
<li id="menu-item-342" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-342"><a href="http://www.zeomega.com/zeomega-media-center/">News &#038; Events</a>
<ul class="sub-menu">
	<li id="menu-item-347" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-347"><a href="http://www.zeomega.com/zeomega-media-center/press-releases-2/">Press Releases</a></li>
	<li id="menu-item-280" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-280"><a href="http://www.zeomega.com/zeomega-media-center/news/">News</a></li>
	<li id="menu-item-281" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-281"><a href="http://www.zeomega.com/zeomega-media-center/press-releases/">Blog</a></li>
	<li id="menu-item-283" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-283"><a href="http://www.zeomega.com/zeomega-media-center/zeomega-events/">Events</a></li>
</ul>
</li>
<li id="menu-item-351" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-351"><a href="http://www.zeomega.com/zeomega-resources/">Resources</a>
<ul class="sub-menu">
	<li id="menu-item-827" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-827"><a href="http://www.zeomega.com/zeomega-resources/case-study-1-title/">Client Success Story</a></li>
	<li id="menu-item-1063" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1063"><a href="http://www.zeomega.com/zeomega-resources/cost-savings-case-study/">Cost Savings Case Study</a></li>
	<li id="menu-item-1051" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1051"><a href="http://www.zeomega.com/zeomega-resources/aco-guide/">ACO Guide</a></li>
	<li id="menu-item-358" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-358"><a href="http://www.zeomega.com/zeomega-resources/zeomega-data-sheets/">Jiva Brochure</a></li>
</ul>
</li>
                </ul>
            </nav>
        </div><!-- end .center-wrap -->
    </header>
<section class="banner-slider">
    <div class="center-wrap">
        <div id="slides">
            <div class="slides_container">
                        <div class="clearfix home-slider-post" id="slider-post-418">
            <div class="one_half">
                <div class="slidertop">Care Management Is Evolving</div>
<div class="slidersub"><a title="Jiva" href="http://www.zeomega.com/?page_id=92">Learn about our integrated solutions</a></div>
            </div>

            <div class="one_half">
                <div class="img-frame full-half"><img src="http://www.zeomega.com/wp-content/themes/Sterling/framework/extended/timthumb/timthumb.php?src=/wp-content/uploads/how-may-i-help-you-300x200.jpg&#038;h=273&#038;w=445" alt="" width="445" height="273"/></div>            </div>
        </div><!-- end .home-slider-post -->
            <div class="clearfix home-slider-post" id="slider-post-414">
            <div class="one_half">
                <div class="img-frame full-half"><img src="http://www.zeomega.com/wp-content/themes/Sterling/framework/extended/timthumb/timthumb.php?src=/wp-content/uploads/medical-team-300x200.jpg&#038;h=273&#038;w=445" alt="" width="445" height="273"/></div>            </div>

            <div class="one_half">
                <div class="slidertop">Evidence-based Is Everything</div>
<div class="slidersub"><a title="Who We Serve" href="http://www.zeomega.com/?page_id=47">Be ready with flexible, scalable solutions</a></div>
            </div>
        </div><!-- end .home-slider-post -->
            <div class="clearfix home-slider-post" id="slider-post-410">
            <div class="one_half">
                <div class="slidertop">Clinical Data Develops One Event at a Time</div>
<div class="slidersub">Improve provider performance with better patient insight</div>
            </div>

            <div class="one_half">
                <div class="img-frame full-half"><a href="http://imagelink" target=""><img src="http://www.zeomega.com/wp-content/themes/Sterling/framework/extended/timthumb/timthumb.php?src=/wp-content/uploads/celebrating-success-300x200.jpg&#038;h=273&#038;w=445" alt="" width="445" height="273"/></a></div>            </div>
        </div><!-- end .home-slider-post -->
            <div class="clearfix home-slider-post" id="slider-post-1360">
            <div class="one_half">
                <div class="slidertop">Connectivity Is Powerful Medicine</div>
<div class="slidersub">Meaningful collaboration begins here</div>
            </div>

            <div class="one_half">
                <div class="img-frame full-half"><img src="http://www.zeomega.com/wp-content/uploads/business-team-445x273.jpg" alt="" width="445" height="273"/></div>            </div>
        </div><!-- end .home-slider-post -->
                </div><!-- end .slides_container -->
        </div><!-- end #slides -->
    </div><!-- end .center-wrap -->
    <div class="shadow top"></div>
    <div class="shadow bottom"></div>
    <div class="tt-overlay"></div>

            <a href="#" class="next tt-sliderbutton">Next</a>
        <a href="#" class="prev tt-sliderbutton">Prev</a>
    </section>



<section id="content-container" class="clearfix">
    <div id="main-wrap" class="main-wrap-slider clearfix">
        <h3>Improving Population Health One Person at a Time</h3>
<div class="two_thirds">
<p>ZeOmega is a leading provider of software for integrated care management. Our solution does more than help care managers track individuals and their treatments. It transforms traditional episodic-based care into an ongoing and collaborative healthcare model that benefits everyone involved: the payer, the provider and the patient or member.</p>
<p><a href="http://www.zeomega.com/zeomega-disease-care-and-utilization-management-software/zeomega_improving_population_health/" rel="attachment wp-att-2963"><img src="http://www.zeomega.com/wp-content/uploads/zeomega_improving_population_health.png" alt="Improving Population Health One Person at a Time" width="325" height="212" class="alignleft size-full wp-image-2963" /></a>Our population health platform enables integrated and shared care management through electronic health record-enabled care plans, point-of-care tools, decision support, user-configurable workflows and portal services.</p>
<p>ZeOmega serves as a “true-north” partner for clients – offering flexible deployment and delivery models. Our innovative platform is designed to integrate workflow, analytics, content and communication capabilities.</p>
<p>We shift the focus from just looking at data and taking isolated and manual actions, to sharing information and taking cooperative, meaningful steps in an automated manner. As a result, we help you improve the quality and cost of healthcare, streamline operations and facilitate communication among stakeholders.</p>
</div>
<div class="one_third">
<a href="http://www.zeomega.com/2013conference" rel="attachment wp-att-3402"><img class="aligncenter size-full wp-image-3402" alt="Join us for the 2013 ZeOmega Client Conference - Transforming Population Healthcare Management" src="http://www.zeomega.com/wp-content/uploads/Client_Conference.jpg" width="541" height="533" /></a></p>
<p>Please join us for the 2013 ZeOmega Client Conference. This event will be a great opportunity for you to stay current with ZeOmega and collaborate with other clients through focused, interactive sessions. <a title="2013 ZeOmega Client Conference" href="http://www.zeomega.com/2013conference/">Click here</a> to learn more!
</div>
<div class="column-clear">&nbsp;</div>
<div class="one_third">
<div class="home-vertical-sidebar"><a href="/?page_id=92" class="tt-icon-link tt-icon icon-globe" target="_self"><br />
<span>Software for Healthcare Management</span><br />
Jiva™ Solutions</a></div>
</div>
<div class="one_third">
<div class="home-vertical-sidebar"><a href="/10-to-win-traits-in-accountable-care-part-1/" class="tt-icon-link tt-icon icon-chat-2" target="_self"><br />
<span>The Latest from Our Blog</span><br />
“10-to-Win” Traits in Accountable Care | Part 1</a></div>
</div>
<div class="one_third">
<div class="home-vertical-sidebar"><a href="/?page_id=1049" class="tt-icon-link tt-icon icon-arrow-down-b" target="_self"><br />
<span>White Paper Series</span><br />
ACO’s Guide to Investing in IT Infrastructure</a></div>
</div>
<div class="column-clear">&nbsp;</div>
<p><img class="aligncenter" alt="Visit ZeOmega at HIMSS 13 Booth #6252!" src="http://www.zeomega.com/wp-content/uploads/Banner_HIMSS.jpg" width="728" height="90" /></p>

    </div><!-- end .main-wrap -->

</section><!-- END content-container -->


<footer>
    <div class="center-wrap tt-relative">
        <div class="footer-content clearfix">
                                <div class="one_third">
                        <div class="sidebar-widget widget_text"><p class="foot-heading">Zeomega Headquarters</p>			<div class="textwidget"><p><img src="http://stage.zeomega.com/wp-content/uploads/zeomega_headquarters.png"></p>
<p>3010 Gaylord Parkway, Suite 210<br />
Frisco, TX 75034<br />
Phone: 214-618-9880 <br />
Fax: 214-975-1258<br/></p>
</div>
		</div>                    </div>
                                        <div class="one_third">
                        <div class="sidebar-widget show_recent"><p class="foot-heading">From Our Blog</p>
                <p class="recent-post-widget-title"><a href="http://www.zeomega.com/10-to-win-traits-in-accountable-care-part-1/">“10-to-Win” Traits in Accountable Care | Part 1</a></p>
                <p class="recent-post-widget-text"><a href="http://www.zeomega.com/10-to-win-traits-in-accountable-care-part-1/">by CJ Fulton, Director of ACO and Government Consulting for ZeOmega

ACOs have forever changed healthcare’s playbook. In ...</a></p>

            
                <p class="recent-post-widget-title"><a href="http://www.zeomega.com/hedis-and-cms-star-ratings-optimizing-benefits/">HEDIS and CMS Star Ratings – Optimizing Benefits</a></p>
                <p class="recent-post-widget-text"><a href="http://www.zeomega.com/hedis-and-cms-star-ratings-optimizing-benefits/">By Sandra Hewett, RN, BSN, CCM

Quality healthcare belongs to the entire health care team, including the patients. Health p...</a></p>

            </div>                    </div>
                                        <div class="one_third">
                        <div class="sidebar-widget tz_tweet_widget"><p class="foot-heading">Latest Tweets</p>
            <!--
            <ul id="twitter_update_list">
                <li><p></p></li>-->
                <ul class="twitterList" id="twitter_update_list"><li><span>Coming May 13-15! The ZeOmega Client Conference: Transforming Population Healthcare Management. More information at <a href="http://t.co/u11R7zpg." target="_blank">http://t.co/u11R7zpg.</a></span><br/><span class="tweet_days">[2 hours ago]</span></li><li><span>ACOs have forever changed healthcare’s playbook. More in our blog: "10-to-Win" Traits in Accountable Care Pt. 1
<a href="http://t.co/Mo58xJZi" target="_blank">http://t.co/Mo58xJZi</a></span><br/><span class="tweet_days">[1 day ago]</span></li></ul>            <!--</ul>-->
            <a href="http://twitter.com/zeomega" id="twitter-link">
                <span>Follow us on Twitter</span>
            </a>

        </div>                    </div>
                            </div><!-- end .footer-content -->
    </div><!-- end .center-wrap -->

    <div class="footer-copyright clearfix">
        <div class="center-wrap clearfix">
    	    <div class="foot-copy">
    	        <p>© 2013 ZeOmega Inc. All rights reserved.</p>
    	    </div><!-- end .foot-copy -->

    	                    <a href="#" id="scroll_to_top" class="link-top">Top</a>
            
                            <ul class="footer-nav">
                    <li id="menu-item-241" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-6 current_page_item menu-item-241"><a href="http://www.zeomega.com/">Home</a></li>
<li id="menu-item-360" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-360"><a href="http://www.zeomega.com/zeomega-privacy-statement/">Privacy Policy</a></li>
<li id="menu-item-242" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-242"><a href="http://www.zeomega.com/zeomega-disease-care-and-utilization-management-software/contact-zeomega-2/">Contact</a></li>
                </ul>
                    </div><!-- end .center-wrap -->
    </div><!-- end .footer-copyright -->

    <div class="shadow top"></div>
    <div class="tt-overlay"></div>
</footer>

</div><!-- end .tt-boxed-layout -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-722295-1']);
  _gaq.push(['_setDomainName', 'zeomega.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<script type="text/javascript">
	   /* <![CDATA[ */
	   document.write (
	      '<img src="http://ci23.actonsoftware.com/acton/bn/2183/visitor.gif?ts='+
	      new Date().getTime()+
	      '&ref='+escape(document.referrer) + '">'
	      );
	   /* ]]> */
</script>


<script type='text/javascript' src='http://www.zeomega.com/wp-content/themes/Sterling/framework/js/slides.min.jquery.js?ver=3.5.1'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-includes/js/comment-reply.js?ver=3.5.1'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-content/themes/Sterling/framework/js/custom-main.js?ver=3.5.1'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-content/themes/Sterling/framework/js/jquery.prettyPhoto.js?ver=3.5.1'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-content/themes/Sterling/framework/js/jquery.superfish.js?ver=3.5.1'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-content/themes/Sterling/framework/js/jquery.cycle.all.min.js?ver=3.5.1'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-content/themes/Sterling/framework/js/jquery.easing.1.3.js?ver=3.5.1'></script>
<script type='text/javascript' src='http://www.zeomega.com/wp-content/themes/Sterling/framework/js/jquery.isotope.js?ver=3.5.1'></script>

    <script type="text/javascript">
        jQuery(document).ready(function($){
            // Homepage slider setup. Issued in the footer to accept user-set variables.
            $('#slides').slides({
                preload: false,
                //preloadImage: 'http://files.truethemes.net/themes/sterling-wp/ajax-loader.gif',
                autoHeight: true,
                effect: 'slide',
                slideSpeed: 500,
                play: 10000,
                randomize: 'false',
                hoverPause: 'true',
                pause: 10000,
                generateNextPrev: 'true'
            });

            // Allows for custom nav buttons to remain outside of #slides container.
            $('.banner-slider .next').click(function(){
                $('#slides .next').click();
            });
            $('.banner-slider .prev').click(function(){
                $('#slides .prev').click();
            });
        });
    </script>

</body>
</html>